debuggins CI issues 2

diff --git a/.github/workflows/playwright.yml b/.github/workflows/playwright.yml
--- a/.github/workflows/playwright.yml
+++ b/.github/workflows/playwright.yml
@@ -36,7 +36,7 @@ jobs:
         if: ${{ !cancelled() }}
         with:
           name: playwright-report
-          path: playwright-report/
+          path: test-report/
           if-no-files-found: ignore # prevent error if report is missing
           retention-days: 30
 
@@ -58,3 +58,8 @@ jobs:
           echo "EMAIL: $EMAIL"
           echo "PASSWORD: $PASSWORD"
           echo "BASE_URL: $BASE_URL"
+
+
+      - name: Check BASE_URL present
+        run: '[ -z "$BASE_URL" ] && echo "BASE_URL is missing" || echo "BASE_URL is set"'
+
